/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:066a2bd607ccd7fd34ec0e447cc5d879:95df1a03af4898931eb3152327fca1ed:e93f688e48c055d4a50dfbfc363a1df4$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string Nebula1 = "Nebula1";
		public const string Nebula2 = "Nebula2";
		public const string Nebula3 = "Nebula3";
		public const string Stars = "Stars";
	}
}