/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:6fd29da32d57351622d365dfdb648e69:92bfc9fd4827b9fd2e3ddc2d1d831cdb:c9d032355133ce0ceec0a2e58f8661ee$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string F5S1 = "F5S1";
		public const string F5S1N = "F5S1N";
		public const string F5S2 = "F5S2";
		public const string F5S2N = "F5S2N";
		public const string F5S3 = "F5S3";
		public const string F5S3N = "F5S3N";
		public const string F5S4 = "F5S4";
		public const string F5S4N = "F5S4N";
		public const string Alien1 = "alien1";
		public const string Alien10001 = "alien10001";
		public const string Alien10002 = "alien10002";
		public const string Alien10003 = "alien10003";
		public const string Alien10004 = "alien10004";
		public const string Alien10005 = "alien10005";
		public const string Alien10006 = "alien10006";
		public const string Alien10007 = "alien10007";
		public const string Alien10008 = "alien10008";
		public const string Alien10009 = "alien10009";
		public const string Alien10010 = "alien10010";
		public const string Alien10011 = "alien10011";
		public const string Alien10012 = "alien10012";
		public const string Alien10013 = "alien10013";
		public const string Alien10014 = "alien10014";
		public const string Alien10015 = "alien10015";
		public const string Alien2 = "alien2";
		public const string Alien3 = "alien3";
		public const string Alien4 = "alien4";
		public const string Aliendropping0001 = "aliendropping0001";
		public const string Aliendropping0002 = "aliendropping0002";
		public const string Aliendropping0003 = "aliendropping0003";
		public const string Aliendropping0004 = "aliendropping0004";
		public const string Aliendropping0005 = "aliendropping0005";
		public const string Aliendropping0006 = "aliendropping0006";
		public const string Aliendropping0007 = "aliendropping0007";
		public const string Aliendropping0008 = "aliendropping0008";
		public const string Aliendropping0009 = "aliendropping0009";
		public const string Alienspaceship = "alienspaceship";
		public const string Blueship1 = "blueship1";
		public const string Blueship2 = "blueship2";
		public const string Blueship3 = "blueship3";
		public const string Blueship4 = "blueship4";
		public const string Greenship1 = "greenship1";
		public const string Greenship2 = "greenship2";
		public const string Greenship3 = "greenship3";
		public const string Greenship4 = "greenship4";
		public const string Orangeship = "orangeship";
		public const string Orangeship2 = "orangeship2";
		public const string Orangeship3 = "orangeship3";
		public const string Smallorange = "smallorange";
		public const string Spacestation = "spacestation";
		public const string St1normal = "st1normal";
		public const string St2normal = "st2normal";
		public const string St3normal = "st3normal";
		public const string Tribase-u1-d0 = "tribase-u1-d0";
		public const string Tribase-u2-d0 = "tribase-u2-d0";
		public const string Tribase-u3-d0 = "tribase-u3-d0";
	}
}