/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:fb5bfa8cdc74c8c4a1ca44dc8467f57f:ab0ee56dc8d68e44be321bb02e09ba42:70337640c72888bf42bfb210bfa91be8$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string 1 = "1";
		public const string 10 = "10";
		public const string 10B = "10B";
		public const string 11 = "11";
		public const string 12 = "12";
		public const string 12B = "12B";
		public const string 13 = "13";
		public const string 13B = "13B";
		public const string 1B = "1B";
		public const string 2 = "2";
		public const string 2B = "2B";
		public const string 3 = "3";
		public const string 4 = "4";
		public const string 4B = "4B";
		public const string 5 = "5";
		public const string 5B = "5B";
		public const string 6 = "6";
		public const string 6B = "6B";
		public const string 7 = "7";
		public const string 8 = "8";
		public const string 8B = "8B";
		public const string 9B = "9B";
		public const string Mech12 = "Mech12";
		public const string Mech12_arm_l = "Mech12_arm_l";
		public const string Mech12_arm_r = "Mech12_arm_r";
		public const string Mech12_head = "Mech12_head";
		public const string Mech12_leg_l = "Mech12_leg_l";
		public const string Mech12_leg_r = "Mech12_leg_r";
		public const string Mech12_shoulder = "Mech12_shoulder";
		public const string Mech12_torso = "Mech12_torso";
		public const string Mech5 = "Mech5";
		public const string Mech5_arm_l = "Mech5_arm_l";
		public const string Mech5_arm_r = "Mech5_arm_r";
		public const string Mech5_foot_l = "Mech5_foot_l";
		public const string Mech5_foot_r = "Mech5_foot_r";
		public const string Mech5_head = "Mech5_head";
		public const string Mech5_leg_l = "Mech5_leg_l";
		public const string Mech5_leg_r = "Mech5_leg_r";
		public const string Mech5_shoulder_l = "Mech5_shoulder_l";
		public const string Mech5_shoulder_r = "Mech5_shoulder_r";
		public const string Mech5_torso = "Mech5_torso";
		public const string Orangeship3 = "orangeship3";
	}
}